package:
  name: py3-apscheduler
  version: "3.11.0"
  epoch: 0
  description: Python job scheduling library
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: apscheduler
  import: apscheduler

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "313"

environment:
  contents:
    packages:
      - py3-supported-build-base-dev
      - py3-setuptools
      - py3-setuptools-scm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/agronholm/apscheduler
      tag: ${{package.version}}
      expected-commit: 6c72a51416893eb0eebbe63d0f2a0151952cab59

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-anyio
        - py${{range.key}}-attrs
        - py${{range.key}}-tenacity
        - py${{range.key}}-tzlocal
        - py${{range.key}}-typing_extensions        
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}        
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}


  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}

update:
  enabled: true
  github:
    identifier: agronholm/apscheduler
