package:
  name: py3-beautifulsoup4
  version: latest
  epoch: 0
  description: "Python package beautifulsoup4"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build beautifulsoup4 wheel
    runs: |
      pip wheel beautifulsoup4 --wheel-dir /package
      pip install --no-index --find-links=/package beautifulsoup4 --target=/app

data:
  paths:
    - path: /app
