package:
  name: py3-blinker
  version: latest
  epoch: 0
  description: "Python package blinker"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build blinker wheel
    runs: |
      pip wheel blinker --wheel-dir /package
      pip install --no-index --find-links=/package blinker --target=/app

data:
  paths:
    - path: /app
