package:
  name: py3-blinker
  version: latest
  epoch: 0
  description: "Python package blinker"
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - build-base

pipeline:
  - name: Build blinker wheel
    runs: |
      pip wheel blinker --wheel-dir /package
      pip install --no-index --find-links=/package blinker --prefix "${{targets.destdir}}"
