package:
  name: py3-certifi
  version: latest
  epoch: 0
  description: "Python package certifi"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - runs: |
      pip wheel certifi --wheel-dir /package
      pip install --no-index --find-links=/package certifi --target=/app

data:
  paths:
    - path: /app
