package:
  name: py3-feedgen
  version: 1.0.0
  epoch: 0
  description: "Python package feedgen"
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: feedgen
  import: feedgen  

data:
  - name: py-versions
    items:
      3.13: "313"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - build-base                

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/lkiesow/python-feedgen
      tag: ${{package.version}}
      expected-commit: 97260abb1793eb164c458c10b493690beb413f6d     

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-lxml
        - py${{range.key}}-python-dateutil        
    pipeline:   
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}

update:
  enabled: true
  github:
    identifier: lkiesow/python-feedgen
