package:
  name: py3-feedgen
  version: 1.0.0
  epoch: 0
  description: "Python package feedgen"
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-lxml    

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - build-base

pipeline:
  - name: Build feedgen wheel
    runs: |
      pip wheel feedgen --wheel-dir /package
      pip install --no-deps --no-index --find-links=/package feedgen --prefix "${{targets.destdir}}"
  - name: Enforce usrmerge layout
    runs: |
      for dir in bin sbin usr/sbin; do
        if [ -d "${{targets.destdir}}/$dir" ]; then
          mkdir -p "${{targets.destdir}}/usr/bin"
          mv "${{targets.destdir}}/$dir/"* "${{targets.destdir}}/usr/bin/" || true
          rm -rf "${{targets.destdir}}/$dir"
        fi
      done     
