package:
  name: py3-feedgenerator
  version: latest
  epoch: 0
  description: "Python package feedgenerator"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build feedgenerator wheel
    runs: |
      pip wheel feedgenerator --wheel-dir /package
      pip install --no-index --find-links=/package feedgenerator --target=/app

data:
  paths:
    - path: /app
