package:
  name: py3-feedgen
  version: 1.0.0
  epoch: 0
  description: Python package feedgen
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - py3-lxml
      - py3-python-dateutil

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - build-base

pipeline:
  - name: Enforce usrmerge layout (early)
    runs: |
      mkdir -p "${{targets.destdir}}/usr"
      if [ -d "${{targets.destdir}}/lib" ] && [ ! -L "${{targets.destdir}}/lib" ]; then
        rm -rf "${{targets.destdir}}/lib"
      fi
      ln -sf usr/lib "${{targets.destdir}}/lib"
  
  - uses: git-checkout
    with:
      repository: https://github.com/lkiesow/python-feedgen
      tag: v${{package.version}}
      expected-commit: 97260abb1793eb164c458c10b493690beb413f6d

  - name: Install feedgen via setup.py directly
    runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - name: Fix usrmerge layout
    runs: |
      if [ -d "${{targets.destdir}}/lib" ] && [ ! -L "${{targets.destdir}}/lib" ]; then
        echo "🔁 Moving /lib contents to /usr/lib to satisfy usrmerge..."
        mkdir -p "${{targets.destdir}}/usr/lib"
        mv "${{targets.destdir}}/lib/"* "${{targets.destdir}}/usr/lib/" || true
        rm -rf "${{targets.destdir}}/lib"
      fi      

test:
  pipeline:
    - uses: python/import
      with:
        python: python3
        imports: |
          import feedgen

update:
  enabled: true
  github:
    identifier: lkiesow/python-feedgen
