package:
  name: py3-gunicorn
  version: latest
  epoch: 0
  description: "Python package gunicorn"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - runs: |
      pip wheel gunicorn --wheel-dir /package
      pip install --no-index --find-links=/package gunicorn --target=/app

data:
  paths:
    - path: /app
