package:
  name: py3-iniconfig
  version: latest
  epoch: 0
  description: "Python package iniconfig"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build iniconfig wheel
    runs: |
      pip wheel iniconfig --wheel-dir /package
      pip install --no-index --find-links=/package iniconfig --target=/app

data:
  paths:
    - path: /app
      type: tree
