package:
  name: py3-itsdangerous
  version: latest
  epoch: 0
  description: "Python package itsdangerous"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build itsdangerous wheel
    runs: |
      pip wheel itsdangerous --wheel-dir /package
      pip install --no-index --find-links=/package itsdangerous --target=/app

data:
  paths:
    - path: /app
