package:
  name: py3-prometheus-flask-exporter
  version: 0.23.2
  epoch: 0
  description: Python package prometheus-flask-exporter
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - py3-flask
      - py3-prometheus-client
      - py3-werkzeug
      - py3-zipp

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - usrmerge
      - busybox
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - build-base

pipeline:
  - name: Enforce usrmerge layout (early)
    runs: |
      mkdir -p "${{targets.destdir}}/usr"
      if [ -d "${{targets.destdir}}/lib" ] && [ ! -L "${{targets.destdir}}/lib" ]; then
        rm -rf "${{targets.destdir}}/lib"
      fi
      ln -sf usr/lib "${{targets.destdir}}/lib"
  
  - uses: git-checkout
    with:
      repository: https://github.com/rycus86/prometheus_flask_exporter
      tag: ${{package.version}}
      expected-commit: f3a43b75f1046b88c72a2cf9d4de5db3a40ccd5c

  - uses: py/pip-build-install
    with:
      python: python3

test:
  pipeline:
    - uses: python/import
      with:
        python: python3
        imports: |
          import prometheus_flask_exporter

update:
  enabled: true
  github:
    identifier: rycus86/prometheus_flask_exporter
