package:
  name: py3-prometheus-client
  version: latest
  epoch: 0
  description: "Python package prometheus-client"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build prometheus-client wheel
    runs: |
      pip wheel prometheus-client --wheel-dir /package
      pip install --no-index --find-links=/package prometheus-client --target=/app

data:
  paths:
    - path: /app
