package:
  name: py3-rss-server
  version: 1.0.13
  epoch: 0
  description: "Modular RSS Server application"
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - build-base

pipeline:
  - name: Write Python project files into the source dir
    runs: |
      # write pyproject.toml next to your .py files
      echo "[build-system]" > "${{package.srcdir}}/pyproject.toml"
      echo "requires = [\"setuptools\", \"wheel\"]" >> "${{package.srcdir}}/pyproject.toml"
      echo "build-backend = \"setuptools.build_meta\"" >> "${{package.srcdir}}/pyproject.toml"

      # write setup.cfg next to them as well
      echo "[metadata]" > "${{package.srcdir}}/setup.cfg"
      echo "name = rss-server" >> "${{package.srcdir}}/setup.cfg"
      echo "version = 1.0.13" >> "${{package.srcdir}}/setup.cfg"

      echo "" >> "${{package.srcdir}}/setup.cfg"
      echo "[options]" >> "${{package.srcdir}}/setup.cfg"
      echo "py_modules =" >> "${{package.srcdir}}/setup.cfg"
      echo "    app" >> "${{package.srcdir}}/setup.cfg"
      echo "    get_latest_release" >> "${{package.srcdir}}/setup.cfg"
      echo "    config" >> "${{package.srcdir}}/setup.cfg"
      echo "    fetch_functions" >> "${{package.srcdir}}/setup.cfg"
      echo "    product_utils" >> "${{package.srcdir}}/setup.cfg"

  - uses: python/build-wheel

  - name: Install rss-server wheel into rootfs
    runs: |
      python3 -m pip install --no-index --find-links="${{targets.contextdir}}" rss-server --root="${{targets.destdir}}"

  - name: Enforce usrmerge layout
    runs: |
      for dir in bin sbin usr/sbin; do
        if [ -d "${{targets.destdir}}/$dir" ]; then
          mkdir -p "${{targets.destdir}}/usr/bin"
          mv "${{targets.destdir}}/$dir/"* "${{targets.destdir}}/usr/bin/" || true
          rm -rf "${{targets.destdir}}/$dir"
        fi
      done

  - name: Cleanup unnecessary Python artifacts
    runs: |
      find "${{targets.destdir}}" -name '*.pyc' -delete
      find "${{targets.destdir}}" -name '*.pyo' -delete
      find "${{targets.destdir}}" -name '__pycache__' -type d -exec rm -rf {} +
      find "${{targets.destdir}}" -name '*.dist-info' -type d -exec rm -rf {} +
