package:
  name: py3-python-dateutil
  version: latest
  epoch: 0
  description: "Python package python-dateutil"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build python-dateutil wheel
    runs: |
      pip wheel python-dateutil --wheel-dir /package
      pip install --no-index --find-links=/package python-dateutil --target=/app

data:
  paths:
    - path: /app
