package:
  name: py3-pyyaml
  version: latest
  epoch: 0
  description: "Python package PyYAML"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build PyYAML wheel
    runs: |
      pip wheel PyYAML --wheel-dir /package
      pip install --no-index --find-links=/package PyYAML --target=/app

data:
  paths:
    - path: /app
      type: tree
