package:
  name: py3-soupsieve
  version: latest
  epoch: 0
  description: "Python package soupsieve"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build soupsieve wheel
    runs: |
      pip wheel soupsieve --wheel-dir /package
      pip install --no-index --find-links=/package soupsieve --target=/app

data:
  paths:
    - path: /app
