package:
  name: py3-tzlocal
  version: latest
  epoch: 0
  description: "Python package tzlocal"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build tzlocal wheel
    runs: |
      pip wheel tzlocal --wheel-dir /package
      pip install --no-index --find-links=/package tzlocal --target=/app

data:
  paths:
    - path: /app
