package:
  name: py3-urllib3
  version: latest
  epoch: 0
  description: "Python package urllib3"
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    packages:
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - gcc
      - musl-dev

pipeline:
  - name: Build urllib3 wheel
    runs: |
      pip wheel urllib3 --wheel-dir /package
      pip install --no-index --find-links=/package urllib3 --target=/app

data:
  paths:
    - path: /app
      type: tree
