name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag msr2.konitzer.dev/wkonitzer/rss_server:latest
   # - name: Log in to the Docker registry
   #   run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login msr2.konitzer.dev -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
   # - name: Push the Docker image
   #   run: docker push msr2.konitzer.dev/wkonitzer/rss_server:latest
